config/routes.rb
Practice::Application.routes.draw do
  root to: 'home#index' 

  get 'home/new' => 'home#new', as: :sign_up
  # get 'home/about' => 'home#about', as: :about
  # get 'home/contact' => 'home#contact', as: :contact

  post '/users' => 'users#create'
  post '/sessions' => 'sessions#create'
  delete '/signout' => 'sessions#destroy', as: :sign_out


  get '/recruiter' => 'recruiters#index'
  get '/newposting' => 'postings#new'
  post '/newposting' => 'postings#create', as: :new_post


  get '/applicant' => 'applicants#index', as: :applicant_home
  get '/myprofile' => 'profile#showmine', as: :my_profile
  patch '/myprofile' => 'profile#update'

  
  get '/like/:id' => 'likes#likesave', as: :like
  get '/dislike/:id' => 'likes#dislikesave', as: :dislike


  post '/searchprofile' => 'profile#search'
  get '/profile/:id' => 'profile#seeprofile', as: :seeprofile

  get '/notification/:id' => 'likes#removenotification', as: :removenotification

  scope 'api', defaults: {format: "json"} do
    get '/' => 'apis#index'
  end
end

app/models/applicant.rb
class Applicant < User
  # has_many :postings, through: :likes
  has_one :profile
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :posting
  belongs_to :profile

  
end

app/models/posting.rb
class Posting < ActiveRecord::Base
  validates_presence_of :title, :description


  belongs_to :recruiter
  has_many :likes
  has_many :profiles, through: :likes

  has_many :posting_tags
  has_many :tags, through: :posting_tags

  def as_json (options={})
    super(:only => [:id, :created_at, :title, :description, :like, :dislike])
  end
end

app/models/posting_tag.rb
class PostingTag < ActiveRecord::Base
  belongs_to :posting
  belongs_to :tag
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  validates_presence_of :applicant_id
  belongs_to :applicant
  has_many :likes
  has_many :postings, through: :likes



  # this determines what gets queried by tag names
  def getTagArray
    # downcase and get taglist array of self
    if self.tag_list 
      tag_list = self.tag_list.downcase.split(" ")
    else
      tag_list = ""
    end
  end

  def getFeed tags
    feed=[]
    tags.each do |tag|
      search = Tag.find_by(name: tag) 
      begin
        feed << search.postings
      rescue
      end
    end
    feed = feed.flatten.uniq.sort

    # gets job created yesterday only
    feed_returned = []
    feed.map do |job|
      # if job.created_at.yday == Time.now.yday
    # if job.created_at.yday == Time.now.yday - 1
        feed_returned << job
      # end
    end

    # this deletes all postings the user has dis/liked
    feed_returned = feed_returned - self.postings 
  end

# returns list of liked jobs that haven't been removed
# from recruiter's feed
  def getLiked
    # gets array of likes
    likes = self.likes.where(notify: true)
    postings = []
    if likes == []
      return likes
    else
      likes.each do |like|
        postings << like.posting
      end
    end
    postings
  end

  def self.search tags
    profiles = []
    allprofiles = Profile.all
    allprofiles.each do |profile|
      if profile.tag_list != nil
        tags.each do |tag|
          if profile.tag_list.include? tag
            profiles << profile
          end 
        end
      end
    end
    # return all profiles that match the search tags
    profiles.uniq
  end
end

app/models/recruiter.rb
class Recruiter < User
  has_many :postings

  def getNotifications recruiterpostings
    notifications = []
    recruiterpostings.each do |posting|
      notifications << posting.likes.where(notify: true)
    end
    notifications.flatten!
  end


end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :posting_tags
  has_many :postings, through: :posting_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  has_secure_password
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController
  skip_before_action :is_logged_in?, :get_current_user
  respond_to :html, :xml, :json

  def index
    # for apis get all postings and return in json format
    @postings = Posting.all
    respond_with (@postings)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  # use login layout
  layout "login"
  # skip check for login
  skip_before_action :is_logged_in?
  
  def index
    # if user is logged in skip login
    if @current_user
      sendMeHome(@current_user)
    end
  end

   # send to the respective homes of applicants or recruiters 
   def sendMeHome user 
      if user.type == "Applicant"
        redirect_to "/applicant"
      else
        redirect_to "/recruiter"
      end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  respond_to :json, :html


  def likesave
    # make like and add to stats on posting
    Like.create(posting_id: params[:id], profile_id: @current_user.profile.id, like: true, notify: true)
    post = Posting.find(params[:id])
    post.like += 1
    post.save    
    
    redirect_to applicant_home_path    
  end

  def dislikesave
    # make like and add to stats on posting
    Like.create(posting_id: params[:id], profile_id: @current_user.profile.id, like: false)
    post = Posting.find(params[:id])
    post.dislike += 1
    post.save
    
    redirect_to applicant_home_path
  end

  def removenotification
    # remove notification when recruiter sees profile
    like = Like.find(params[:id])
    like.update(notify: false)

    redirect_to seeprofile_path(like.profile_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :is_logged_in?
  def create
    # type indicates sub class of applicant or recruiter 
    user = User.new(params.require(:user).permit(:email, :name, :type, :password, :password_confirmation))
    user.email.downcase!
    user.name.downcase!
    # saves users email in downcase form
    if user.save
      # saves user id to session to start
      session[:user_id] = user.id.to_s
      # direct to applicant or recruiter
      sendMeHomeAndCreateProfile(user)
    else
      redirect_to root_path
    end
  end

  # send user to respective home and make profile if is applicant
  def sendMeHomeAndCreateProfile user 
      if user.type == "Applicant"
        Profile.create(applicant_id: user.id)
        redirect_to "/applicant"
      else
        redirect_to "/recruiter"
      end
  end
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def allPossibleTags
    Tag.all
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/recruiters_helper.rb
module RecruitersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_login.html.erb
<div id="title-login">Swink</div>
<%= form_for(:session, url: sessions_path, html: {class: "form-horizontal", role: "form"})  do |f|  %>
    <div class="form-group">
        <%= f.label :email, class: "col-sm-1 control-label sr-only"  %>
        <div class="col-sm-10">
            <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
 	    </div>
    </div>
 	<div class="form-group">
         <%= f.label :password, class: "col-sm-1 control-label sr-only" %>
        <div class="col-sm-10">
            <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
        </div>
    </div>
     <div class="form-group" id="login_div" > 
         <%= f.submit "Log In", class: "btn btn-default", id: "login_button" %>
          <div class="btn btn-default" id="show-sign-up">Sign Up</div>
     </div>
<% end %> 

app/views/home/_signup.html.erb
<div id="title-login">Sign Up</div>
<div id="signup_form">
  <%= form_for(:user, url: users_path, html: {class: "form-horizontal", role: "form"})  do |f|  %>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-1 control-label sr-only"  %>
    <div class="col-sm-10">
      <%= f.email_field :email, class: "form-control", placeholder: "Enter Email", id: "create_email"%>
 	  </div>
  </div>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-1 control-label sr-only"  %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control", placeholder: "Enter Name", id: "create_name"%>
 	  </div>
  </div>

 	<div class="form-group">
    <%= f.label :password, class: "col-sm-1 control-label sr-only" %>
    <div class="col-sm-10">
      <%= f.password_field :password, class: "form-control", placeholder: "Enter Password", id: "create_password"%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password, class: "col-sm-1 control-label sr-only" %>
    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password", id: "password_confirm"%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :type, class: "col-sm-1 control-label sr-only"  %>
    <div class="col-sm-10">
      <%= f.select(:type, [["Applicant", "Applicant"],["Recruiter","Recruiter"]], {}, class: "form-control") %>
    </div>
  </div>

  <div class="form-group" id="login_div" > 
    <%= f.submit "Create Account", class: "btn btn-default", id: "login_button" %>
    <div class="btn btn-default" id="show-login">Log In</div>
  </div>

<% end %> 

app/views/home/index.html.erb
<div class="container" id="no-border">
		  <div id="login-form">
		  	<%= render 'login' %>
		  </div>
		  <div id="signup-form">
		  	<%= render 'signup' %>
		  </div>
</div>