config/routes.rb
Practice::Application.routes.draw do
  root to: 'home#index' 

  get 'home/new' => 'home#new', as: :sign_up
  # get 'home/about' => 'home#about', as: :about
  # get 'home/contact' => 'home#contact', as: :contact

  post '/users' => 'users#create'
  post '/sessions' => 'sessions#create'
  delete '/signout' => 'sessions#destroy', as: :sign_out


  get '/recruiter' => 'recruiters#index'
  get '/newposting' => 'postings#new'
  post '/newposting' => 'postings#create', as: :new_post


  get '/applicant' => 'applicants#index', as: :applicant_home
  get '/myprofile' => 'profile#showmine', as: :my_profile
  patch '/myprofile' => 'profile#update'

  
  get '/like/:id' => 'likes#likesave', as: :like
  get '/dislike/:id' => 'likes#dislikesave', as: :dislike


  post '/searchprofile' => 'profile#search'
  get '/profile/:id' => 'profile#seeprofile', as: :seeprofile

  get '/notification/:id' => 'likes#removenotification', as: :removenotification

  scope 'api', defaults: {format: "json"} do
    get '/' => 'apis#index'
  end
end

app/models/applicant.rb
class Applicant < User
  # has_many :postings, through: :likes
  has_one :profile
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :posting
  belongs_to :profile

  
end

app/models/posting.rb
class Posting < ActiveRecord::Base
  validates_presence_of :title, :description


  belongs_to :recruiter
  has_many :likes
  has_many :profiles, through: :likes

  has_many :posting_tags
  has_many :tags, through: :posting_tags

  def as_json (options={})
    super(:only => [:id, :created_at, :title, :description, :like, :dislike])
  end
end

app/models/posting_tag.rb
class PostingTag < ActiveRecord::Base
  belongs_to :posting
  belongs_to :tag
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  validates_presence_of :applicant_id
  belongs_to :applicant
  has_many :likes
  has_many :postings, through: :likes



  # this determines what gets queried by tag names
  def getTagArray
    # downcase and get taglist array of self
    if self.tag_list 
      tag_list = self.tag_list.downcase.split(" ")
    else
      tag_list = ""
    end
  end

  def getFeed tags
    feed=[]
    tags.each do |tag|
      search = Tag.find_by(name: tag) 
      begin
        feed << search.postings
      rescue
      end
    end
    feed = feed.flatten.uniq.sort

    # gets job created yesterday only
    feed_returned = []
    feed.map do |job|
      # if job.created_at.yday == Time.now.yday
    # if job.created_at.yday == Time.now.yday - 1
        feed_returned << job
      # end
    end

    # this deletes all postings the user has dis/liked
    feed_returned = feed_returned - self.postings 
  end

# returns list of liked jobs that haven't been removed
# from recruiter's feed
  def getLiked
    # gets array of likes
    likes = self.likes.where(notify: true)
    postings = []
    if likes == []
      return likes
    else
      likes.each do |like|
        postings << like.posting
      end
    end
    postings
  end

  def self.search tags
    profiles = []
    allprofiles = Profile.all
    allprofiles.each do |profile|
      if profile.tag_list != nil
        tags.each do |tag|
          if profile.tag_list.include? tag
            profiles << profile
          end 
        end
      end
    end
    # return all profiles that match the search tags
    profiles.uniq
  end
end

app/models/recruiter.rb
class Recruiter < User
  has_many :postings

  def getNotifications recruiterpostings
    notifications = []
    recruiterpostings.each do |posting|
      notifications << posting.likes.where(notify: true)
    end
    notifications.flatten!
  end


end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :posting_tags
  has_many :postings, through: :posting_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  has_secure_password
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController
  skip_before_action :is_logged_in?, :get_current_user
  respond_to :html, :xml, :json

  def index
    # for apis get all postings and return in json format
    @postings = Posting.all
    respond_with (@postings)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  # use login layout
  layout "login"
  # skip check for login
  skip_before_action :is_logged_in?
  
  def index
    # if user is logged in skip login
    if @current_user
      sendMeHome(@current_user)
    end
  end

   # send to the respective homes of applicants or recruiters 
   def sendMeHome user 
      if user.type == "Applicant"
        redirect_to "/applicant"
      else
        redirect_to "/recruiter"
      end
  end
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def allPossibleTags
    Tag.all
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/recruiters_helper.rb
module RecruitersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/applicants.html.erb
<!DOCTYPE html>
<html ng-app="ApplicantApp">
<head>
  <title>Swink</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body class="applicants-body" ng-controller="applicantCtrl">
	<nav class="navbar" role="navigation">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	      	 <li class="inline button" ng-init="seeFeed=true" ng-click="toggle(seeFeed, 'f'); load()" ng-class="{selected: seeFeed}">Feed<span ng-if="counter" id="counter">({{counter}})</span></li>
	        <li class="inline button" ng-click="toggle(seeLikedJobs, 'l'); load()"
	ng-init="seeLikedJobs=false" ng-class="{selected: seeLikedJobs}">Active Notifications</li>
	         <li class="inline button" ng-init="seeProfile=false" ng-click="toggle(seeProfile, 'p'); getProfileInfo()" ng-class="{selected: seeProfile}">Edit Profile</li>
	         <li class="inline button lineheight"><a href="/signout"><%= link_to "Log Out", sign_out_path, method: :delete, :id=>"keepdark"%></a></li>
	      </ul>
	      </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>


<%= yield %>

<script>
	angular.module('ApplicantApp', [])
	.config(["$httpProvider", function($httpProvider){
	  $httpProvider.defaults.headers.common['X-CSRF-Token'] = $('meta[name=csrf-token]').attr('content')
	}])

	.controller('applicantCtrl', ['$scope', '$timeout', '$http', function($scope, $timeout, $http) {
		console.log("Angular Ready");
		
		// when first landing or refreshing get data
		$scope.load = function(){$http.get('/applicant.json').success(function(data){
				$scope.link = data.link;
				$scope.feed = data.feed;
				if($scope.feed!=null){
					$scope.counter = data.feed.length;
				}
				$scope.liked = data.liked;
				$scope.name = data.name;
				$scope.email = data.email;
				$scope.alltags = data.alltags;
			});
		}
		$scope.load();

		$scope.getProfileInfo = function(){
			$http.get('/myprofile.json').success(function(data){
				$scope.link = data.link;
				// highlights in red already selected and sets up array and checks for existing tags
				if (data.tag_list != null){
					$scope.tagArray = data.tag_list.split(" ");
				}
			});
		}

		$scope.saveProfile = function(link, tag_list){
			$http.patch('/myprofile.json', {link: link, tag_list: tag_list}).success(function(data){
					$http.get('/applicant.json').success(function(data){
						console.log(data);
						$scope.profileData = data;
						$scope.feed = data.feed;
						$scope.liked = data.feed;
						$scope.toggle(false,"f");
					});
			});
		}

		// like and dislike functions to create rows
		$scope.like = function(id){
			$scope.id = id;
			// gives time for sliding animation
			$timeout(function () {
				console.log(id);
	            $http.get('/like/'+$scope.id).success(function(data){
	            	$scope.load();
	            });
			}, 100);

			
		}
		$scope.dislike = function(id){
			$scope.id = id;
			// gives time for sliding animation
			$timeout(function () {
	            $http.get('/dislike/'+id).success(function(data){
	            	$scope.load();
	            });
			}, 100);
		}



		// toggle menu
		$scope.toggle = function(x,y){
			if(x==false){
				if(y=="f")
				{
					$scope.seeFeed=true;
					$scope.seeLikedJobs=false;
					$scope.seeProfile=false;
				}
				else if(y=="l"){
					$scope.seeFeed=false;
					$scope.seeLikedJobs=true;
					$scope.seeProfile=false;
				}
				else if(y=="p"){
					$scope.seeFeed=false;
					$scope.seeLikedJobs=false;
					$scope.seeProfile=true;
				}
			}
		}

		// initialize empty search array
		$scope.tagArray = [];

		$scope.addTag = function(tag, addRemove){
			// add tag from array
			if (addRemove == true){ 
				$scope.tagArray.push(tag);
			}
			// remove tag from array
			else
			{
				var index = $scope.tagArray.indexOf(tag);
				$scope.tagArray.splice(index, 1);
			}
			console.log($scope.tagArray);			
		}

		// to control toggle of tag buttons
		$scope.checkArray = function(tagName){
			// tag in array
			if ($scope.tagArray.indexOf(tagName) != -1){
				return false;
			}
			// tag not in array
			else{
				return true;
			}
		}

		// reset selected
		$scope.reset = function(){
			$scope.tagArray=[];
		}


	 }]);
</script>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Swink</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="login">
	

  <%= yield %>

<!-- 
<p>Hello</p>
<button id="button">BUTTON</button>
 -->

<script>


$(function(){
  $("#show-sign-up").click(function() {
    $("#no-border").css("height","550px");
    $("#no-border").css("margin-top", "50px");
    $("#login-form").hide();
    $("#signup-form").fadeIn();
  });

  $("#show-login").click(function(){
    $("#no-border").css("height", "400px");
    $("#no-border").css("margin-top", "100px");
    $("#login-form").fadeIn();
    $("#signup-form").hide();
  });
});


</script>
</body>
</html>

app/views/layouts/recruiters.html.erb
<!DOCTYPE html>
<html ng-app="RecruiterApp">
<head>
  <title>Swink</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.min.js"></script>
  <%= csrf_meta_tags %>
  
</head>

<body class="recruiters-body" ng-controller="recruiterCtrl">

<nav class="navbar" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="inline button" ng-click="toggle(newPosting, 'n')"
ng-init="newPosting=false" ng-class="{selected: newPosting}">Create Posting</li>
         <li class="inline button" ng-init="searchDiv=false" ng-click="toggle(searchDiv, 's')" ng-class="{selected: searchDiv}">Search Applicants</li>
         <li class="inline button"  ng-init="showPosting=true" ng-click="toggle(showPosting, 'p')", ng-class="{selected: showPosting}">My Postings</li>
         <li class="inline button" ng-init="showNotifications=false" ng-click="toggle(showNotifications, 'not'); getPostings()" ng-class="{selected: showNotifications}">Notifications<span ng-if="counter" id="counter">({{counter}})</span></li>
         <li class="inline button lineheight"><a href="/signout"><%= link_to "Log Out", sign_out_path, method: :delete, :id=>"keepdark"%></a></li>
      </ul>
      </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

<script>
	angular.module('RecruiterApp', [])
	.config(["$httpProvider", function($httpProvider){
	  $httpProvider.defaults.headers.common['X-CSRF-Token'] = $('meta[name=csrf-token]').attr('content')
	}])
	.controller('recruiterCtrl', ['$scope', '$http', function($scope, $http) {
		console.log("Angular Ready");

		// initialize empty search array
		$scope.tagArray = [];

		// add or remove tags for search
		$scope.addTag = function(tag, addRemove){
			// add tag from array
			if (addRemove == true){ 
				$scope.tagArray.push(tag);
			}
			// remove tag from array
			else
			{
				var index = $scope.tagArray.indexOf(tag);
				$scope.tagArray.splice(index, 1);
			}
			console.log($scope.tagArray);			
		}

		// reset selected
		$scope.reset = function(){
			$scope.tagArray=[];
			$scope.postingTagArray =[];
		}

		// to control toggle of tag buttons
		$scope.checkArray = function(tagName){
			// tag in array
			if ($scope.tagArray.indexOf(tagName) != -1){
				return false;
			}
			// tag not in array
			else{
				return true;
			}
		}

		// initialize empty postingTagArray
		$scope.postingTagArray =[];

		// Adding tag to array of postingtags
		$scope.postingAddTag = function(tag, addRemove){
			// add tag from array
			if (addRemove == true){ 
				$scope.postingTagArray.push(tag);
			}
			// remove tag from array
			else
			{
				var index = $scope.postingTagArray.indexOf(tag);
				$scope.postingTagArray.splice(index, 1);
			}
			console.log($scope.postingTagArray);
		}

		// To control toggle of posting array
		$scope.checkPostingArray = function(tagName){
			// tag in posting array
			if ($scope.postingTagArray.indexOf(tagName) != -1){
				return false;
			}
			// tag not in posting array
			else{
				return true;
			}
		}

		// Make new posting
		$scope.makeNewPosting = function(title, description, postingTagArray){
			console.log("making");

			// exit if no tags are inserted
			if (postingTagArray.length == 0){
				return;
			}
			else{
				$http.post('/newposting', {title: title, description: description, postingTagArray: postingTagArray}).success(function(data){
						$scope.newPosting = !$scope.newPosting;
						$scope.getPostings();
						$scope.toggle(false,"p");
						$scope.reset();
				});
			}
		}

		// Runs when loaded (fetch new page data)
		// Load all posted jobs by this recruiter
		// Gets total likes and dislikes
		// gets all tags in tags table
		// gets notifications and all associated 
		// user data
		// gets all of recruiters postings
		$scope.getPostings = function(){
			$http.get('/recruiter.json').success(function(data){
				$scope.postings = data.postings;
				$scope.lstat = 0;
				$scope.dstat = 0;
				if (data.postings.length>0){
					for (var i = 0; i < data.postings.length; i++){
						$scope.lstat += data.postings[i].like;
						$scope.dstat += data.postings[i].dislike; 
					}
				}
				$scope.tags = data.tags;
				$scope.notifications = data.notifications;
				if($scope.notifications!=null){
					$scope.counter=$scope.notifications.length;
				}
				// related data for notifications
				$scope.names = data.names;
				$scope.emails = data.emails;
				$scope.profilesA = data.profiles;
				$scope.taglistsA = data.taglists;
				$scope.linksA = data.linkarray;
			});
		}


		// Get all postings made by recruiter
		$scope.getPostings();

		// Search for applicants
		$scope.search = function(tags){
			console.log(tags.length);
			console.log("searching");
			// Skip search if no tags selected
			if(tags.length == 0){
				return;
			}
			else
			{
				$http.post('/searchprofile', {tags: tags}).success(function(data){
					// get applicant's data
					$scope.applicants = data.profiles;
					$scope.searchnames = data.names;
					$scope.searchemails = data.emails;
					$scope.searchlinks = data.links;
					$scope.searchtaglists = data.tag_lists;
				});
			}
		}

		// Notifications
		$scope.removeNotification = function(id){
			console.log("see profile");
			// update after user closes profile
			$http.get('/notification/'+id).success(function(data){
					$scope.getPostings();
			});
		}

		// for toggling through menu (on/off)
		$scope.toggle = function(x, y){
			if(x==false){
				if(y=="n")
				{	
					$scope.newPosting=true;
					$scope.showPosting=false;
					$scope.searchDiv=false;
					$scope.showNotifications=false;
				}
				else if(y=="p")
				{
					$scope.newPosting=false;
					$scope.showPosting=true;
					$scope.searchDiv=false;
					$scope.showNotifications=false;
				}
				else if(y=="s")
				{
					$scope.newPosting=false;
					$scope.showPosting=false;
					$scope.searchDiv=true;
					$scope.showNotifications=false;
				}
				else if(y=="not")
				{
					$scope.newPosting=false;
					$scope.showPosting=false;
					$scope.searchDiv=false;
					$scope.showNotifications=true;
				}
			}
		}

		$scope.carousel=[];
		$scope.forwards = function(x){
			console.log("forwards from");
			console.log(x);
			// hides all
			for(person in $scope.carousel){
				$scope.carousel[person]=false;
			}
			// shows next or loops back to first
			if (x < $scope.applicants.length-1){
				$scope.carousel[x+1]=true;
			}
			else{
				$scope.carousel[0]=true;
			}
		}

		$scope.backwards = function(x){
			console.log("backwards from");
			console.log(x);
			// hide all
			for(person in $scope.carousel){
				$scope.carousel[person]=false;
			}
			// shows previous or loops back to first
			if (x != 0){
				$scope.carousel[x-1]=true;
			}
			else{
				$scope.carousel[$scope.applicants.length-1]=true;
			}
		}

		$scope.ncarousel=[];
		$scope.nforwards = function(x){
			console.log("forwards from");
			console.log(x);
			// hides all
			for(n in $scope.ncarousel){
				$scope.ncarousel[n]=false;
			}
			// shows next or loops back to first
			if (x < $scope.notifications.length-1){
				$scope.ncarousel[x+1]=true;
			}
			else{
				$scope.ncarousel[0]=true;
			}
		}

		$scope.nbackwards = function(x){
			console.log("backwards from");
			console.log(x);
			// hide all
			for(n in $scope.ncarousel){
				$scope.ncarousel[n]=false;
			}
			// shows previous or loops back to first
			if (x != 0){
				$scope.ncarousel[x-1]=true;
			}
			else{
				$scope.ncarousel[$scope.notifications.length-1]=true;
			}
		}
	 }]);

	
</script>
</body>
</html>